Add GroupsList runtime function
heroiclabs/nakama-common pull request #31
Opened 2021-06-09 18:37 UTC by sesposito

2021-06-14 21:27 UTC, zyro requested changes

2021-06-14 21:27 UTC, zyro commented on api/api.proto
> +  google.protobuf.BoolValue open = 6;
Re-numbering may need discussion.

2021-06-16 08:59 UTC, sesposito commented on api/api.proto
> +  google.protobuf.BoolValue open = 6;
I've changed the order so that the new fields are appended.

2021-06-17 15:18 UTC, zyro approved these changes

2021-06-17 18:54 UTC, merged