Added a generic State parameter to MatchHandler and handler functions
heroiclabs/nakama-common pull request #53
Opened 2022-01-27 22:37 UTC by bananu7

My proposal for solving #52

2022-01-27 22:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/heroiclabs/nakama-common?pullRequest=53) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/heroiclabs/nakama-common?pullRequest=53) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/heroiclabs/nakama-common?pullRequest=53) it.</sub>

2022-01-27 22:43 UTC, bananu7 commented
The force push was fixing the return type which I forgot about initially.

2022-01-28 15:43 UTC, sesposito requested changes
Good suggestion to better leverage the use of generics 👍, left a minor comment.

2022-01-28 15:43 UTC, sesposito commented on index.d.ts
> +    export interface MatchInitFunction<State> {
Can we add generic default here as well to improve backwards compatibility please?
```suggestion
    export interface MatchInitFunction<State = MatchState> {
```
Same for the following MatchHandler function definitions

2022-01-28 20:16 UTC, bananu7 commented on index.d.ts
> +    export interface MatchInitFunction<State> {
I thought about this initially, and didn't end up adding that because I figured that one default will trickle down the tree. But it's probably a good point that if those types are directly used by the users, making it default everywhere is a safer option.

2022-01-31 10:36 UTC, sesposito approved these changes

2022-02-15 11:40 UTC, zyro approved these changes

2022-02-15 11:41 UTC, merged